# Display Ross's robot No 1
print("Please enter a character for the eyes")
robot_eyes = input()
print("    ##########")
print("   ## ",robot_eyes," ",robot_eyes,"##")
print("   ##   ||   ##")
print("    # \\----/ #")
print("    ##########")
print(" ################")
print(" ## ##      ## ##")
print(" ## ########## ##")
print(" ## ## ####### ##")
print(" ## ########## ##")
print(" \"\" ########## \"\"")
print("    ########## ")
print("    ########## ")
print("    ########## ")
print("    ########## ")
print("       O  O")
print("\n")
# Display Ross's robot No 2 - as 1 but using \t
print("\t    ##########")
print("\t   ##  @  @  ##")
print("\t   ##   ||   ##")
print("\t    # \\----/ #")
print("\t    ##########")
print("\t ################")
print("\t ## ##      ## ##")
print("\t ## ########## ##")
print("\t ## ## ####### ##")
print("\t ## ########## ##")
print("\t \"\" ########## \"\"")
print("\t    ########## ")
print("\t    ########## ")
print("\t    ########## ")
print("\t    ########## ")
print("\t       O  O")
print("\n")
# Display Ross's robot No 3 - using more \ts (like it moving across the page!)
print("\t\t\t\t    ##########")
print("\t\t\t\t   ##  @  @  ##")
print("\t\t\t\t   ##   ||   ##")
print("\t\t\t\t    # \\----/ #")
print("\t\t\t\t    ##########")
print("\t\t\t\t ################")
print("\t\t\t\t ## ##      ## ##")
print("\t\t\t\t ## ########## ##")
print("\t\t\t\t ## ## ####### ##")
print("\t\t\t\t ## ########## ##")
print("\t\t\t\t \"\" ########## \"\"")
print("\t\t\t\t    ########## ")
print("\t\t\t\t    ########## ")
print("\t\t\t\t    ########## ")
print("\t\t\t\t    ########## ")
print("\t\t\t\t       O  O")